server.port=7000

logging.level.org.springframework.security=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/payanam	
spring.datasource.username=flavian
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=loggers

#To generate RSA public and private keys
#Open cmd and type "openssl"
#Then "genrsa -out private.pem 2048" -> this will create a pem file in your current User profile location
#Then extract public key from the generated key by "rsa -in private.pem -out public.pem -outform PEM -pubout"
