server.port=9000

logging.level.org.springframework.security=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/payanam	
spring.datasource.username=flavian
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=loggers

spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true